import type { CommandDefinition, CommandType } from './types'

export const commandDefinitions: Record<CommandType, CommandDefinition> = {
  think: {
    id: 'think',
    label: '考える',
    description: 'ひらめき候補を3つ見つける',
    icon: '◇',
    summary: '要件の輪郭がはっきりし、次の一手が見えてきた。',
    recommendation: '次は「作る」で、小さな機能から形にしましょう。',
    statusChanges: { motivation: 1, technicalDebt: -2, stamina: -5 },
    changedFiles: ['TODO.md'],
    logs: ['要件を整理しました', '優先度の高いTODOを確認しました'],
  },
  build: {
    id: 'build',
    label: '作る',
    description: '機能の元を選んで育てる',
    icon: '＋',
    summary: '画面一覧の実装が進んだ。',
    recommendation: '次は「確かめる」で動作確認しましょう。',
    statusChanges: { completion: 10, stamina: -15, technicalDebt: 5 },
    changedFiles: ['src/App.tsx', 'src/App.css'],
    logs: ['画面コンポーネントを更新しました', 'スタイルを調整しました'],
  },
  verify: {
    id: 'verify',
    label: '確かめる',
    description: '完成した機能の調子をみる',
    icon: '✓',
    summary: '品質チェックが完了し、不安な箇所を減らせた。',
    recommendation: '問題がなければ「作る」で次の機能へ進みましょう。',
    statusChanges: { completion: 5, stamina: -10, technicalDebt: -5 },
    changedFiles: [],
    logs: ['test: passed', 'lint: passed', 'typecheck: passed'],
  },
  check: {
    id: 'check',
    label: '確かめる',
    description: '外部で実行した確認結果を取り込む',
    icon: '✓',
    summary: '確認コマンドの結果を記録した。',
    recommendation: '結果を確認して、次の修正または実装へ進みましょう。',
    statusChanges: {},
    changedFiles: [],
    logs: [],
  },
  organize: {
    id: 'organize',
    label: '整える',
    description: 'ひと休みして状況を片づける',
    icon: '≡',
    summary: '散らかった情報を整え、落ち着いて再開できる状態になった。',
    recommendation: '視界が晴れました。「考える」で次の目標を決めましょう。',
    statusChanges: { stamina: 10, motivation: 1, technicalDebt: -8 },
    changedFiles: ['README.md', 'TODO.md'],
    logs: ['ドキュメントを整理しました', '作業コンテキストを更新しました'],
  },
  release: {
    id: 'release',
    label: 'リリース判定',
    description: '現在の完成度と確認状態からリリース可能性を評価する',
    icon: '★',
    summary: '現在のリリース準備状況を評価した。',
    recommendation: '懸念とおすすめ行動を確認しましょう。',
    statusChanges: {},
    changedFiles: [],
    logs: [],
  },
}
